### ISSUE TITLE
await message.mentionList() 这句报错

### ISSUE THREAD

**Issue by nsnsqk** [wechaty/puppet#211]
'Error: filterValue not found for filterKey: id\n' +
    '    at PuppetPadlocal.contactQueryFilterFactory (D:\\IdeaProjects\\yang\\robot-demo\\node_modules\\wechaty-puppet\\src\\mixins\\contact-mixin.ts:232:15)\n' +
    '    at async Function.find (D:\\IdeaProjects\\yang\\robot-demo\\node_modules\\wechaty\\src\\user-modules\\contact.ts:123:25)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async WechatifiedUserClass.mentionList (D:\\IdeaProjects\\yang\\robot-demo\\node_modules\\wechaty\\src\\user-modules\\message.ts:666:26)\n' +
    '    at async WechatyImpl.onMessage (D:\\IdeaProjects\\yang\\robot-demo\\main.ts:88:38)'

**Comment by wogengshuai** [comment]
我也是这个问题，解决了吗
